// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASDTgA7-IkWCqSIyPQ7TrmGY5QDIz5Ipc',
    appId: '1:252335844399:web:0fb1a009cbb1b2db966ada',
    messagingSenderId: '252335844399',
    projectId: 'instagram-clone-826b3',
    authDomain: 'instagram-clone-826b3.firebaseapp.com',
    storageBucket: 'instagram-clone-826b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvc7yX-RQG8hLhUUWcgXYRaeTXAx4wKVk',
    appId: '1:252335844399:android:1c356f844e4d4f18966ada',
    messagingSenderId: '252335844399',
    projectId: 'instagram-clone-826b3',
    storageBucket: 'instagram-clone-826b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2396e0j1V2lpqFX2WYZf7tr3Uqptpe3k',
    appId: '1:252335844399:ios:f25756c8df8de6fb966ada',
    messagingSenderId: '252335844399',
    projectId: 'instagram-clone-826b3',
    storageBucket: 'instagram-clone-826b3.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
